language: c++

services:
  - docker

before_install:
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --registry-mirror=https://mirror.gcr.io"'
  - sudo service docker restart
  - docker build -t grpc-va-server:latest .

install: skip

script:
  - docker run --rm grpc-va-server:latest ./test_va_server
