language: c++

os: linux
dist: bionic

addons:
  apt:
    update: true
    packages:
      - cmake
      - pkg-config
      - libopencv-dev

compiler: gcc

before_install:
  - bash tools/install_grpc.sh

script:
  - bash tools/build.sh

after_success:
  - ./build/test-va-server
